#!/usr/bin/env python3
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "findingmodel",
# ]
# ///
"""Post-process finding model stubs generated by make-stub-model.

make-stub-model creates valid finding models but doesn't add contributors,
and the AI sometimes renames findings or generates poor descriptions. This
script fixes those issues.

Usage (single file):
    uv run scripts/finding_authoring/fix_stub.py \
        defs/pneumothorax.fm.json \
        --name "pneumothorax" \
        --description "Air in the pleural space." \
        --synonyms "air leak" "collapsed lung" \
        --contributor hoodcm

Usage (batch via JSON config on stdin):
    uv run scripts/finding_authoring/fix_stub.py --batch < config.json

Batch JSON format:
{
    "contributor": "hoodcm",
    "models": {
        "defs/pneumothorax.fm.json": {
            "name": "pneumothorax",
            "description": "Air in the pleural space.",
            "synonyms": ["air leak", "collapsed lung"]
        },
        "defs/atelectasis.fm.json": {
            "name": "atelectasis",
            "description": "Partial or complete collapse of lung parenchyma."
        }
    }
}

Output: prints "name|oifm_id" for each processed file (useful for CSV updates).
"""

import argparse
import json
import sys
from pathlib import Path

# Known contributors — add more as needed
CONTRIBUTORS = {
    "hoodcm": {
        "github_username": "hoodcm",
        "email": "chood@mgh.harvard.edu",
        "name": "C. Michael Hood, MD",
        "organization_code": "MGB",
    },
    "HeatherChase": {
        "github_username": "HeatherChase",
        "name": "Heather Chase",
        "organization_code": "MSFT",
    },
    "radngandhi": {
        "github_username": "radngandhi",
        "name": "Namita Gandhi, MD",
        "organization_code": "RSNA",
    },
    "talkasab": {
        "github_username": "talkasab",
        "email": "talkasab@partners.org",
        "name": "Tarik Alkasab, MD, PhD",
        "organization_code": "MGB",
    },
    "OIDM": {
        "name": "Open Imaging Data Model",
        "code": "OIDM",
    },
    "GMTS": {
        "name": "Radiology Gamuts Ontology",
        "code": "GMTS",
        "url": "https://gamuts.net/",
    },
    "CDE": {
        "name": "ACR/RSNA Common Data Elements Project",
        "code": "CDE",
    },
    "MGB": {
        "name": "Mass General Brigham",
        "code": "MGB",
    },
    "MSFT": {
        "name": "Microsoft",
        "code": "MSFT",
    },
    "RSNA": {
        "name": "Radiological Society of North America",
        "code": "RSNA",
    },
}


def fix_model(filepath: str, overrides: dict, contributor_key: str | list[str]) -> str:
    """Fix a single stub model file. Returns 'name|oifm_id'.

    contributor_key can be a single key or a list of keys for multiple contributors.
    """
    p = Path(filepath)
    if not p.exists():
        print(f"ERROR: {filepath} not found", file=sys.stderr)
        return ""

    # Parse with findingmodel for validation, then work with dict for flexibility
    try:
        from findingmodel import FindingModelFull

        model = FindingModelFull.model_validate_json(p.read_text())
        d = json.loads(model.model_dump_json(exclude_none=True))
    except Exception:
        # Fallback: just load as raw JSON
        d = json.loads(p.read_text())

    old_name = d.get("name", "")

    # Apply overrides
    new_name = overrides.get("name", old_name)
    if "name" in overrides:
        d["name"] = new_name
    if "description" in overrides:
        d["description"] = overrides["description"]
    if "synonyms" in overrides:
        d["synonyms"] = overrides["synonyms"]
    if "tags" in overrides:
        d["tags"] = overrides["tags"]

    # Fix attribute descriptions if name changed
    if old_name.lower() != new_name.lower():
        for attr in d.get("attributes", []):
            if old_name in attr.get("description", ""):
                attr["description"] = attr["description"].replace(old_name, new_name)
            for val in attr.get("values", []):
                if old_name in val.get("description", ""):
                    val["description"] = val["description"].replace(
                        old_name, new_name
                    )

    # Add contributors (supports single key or list of keys)
    keys = [contributor_key] if isinstance(contributor_key, str) else contributor_key
    if keys:
        contributors = []
        for key in keys:
            if key in CONTRIBUTORS:
                contributors.append(CONTRIBUTORS[key])
            else:
                print(f"WARNING: Unknown contributor '{key}', skipping", file=sys.stderr)
        if contributors:
            d["contributors"] = contributors

    # Write back in canonical format (2-space indent, no trailing newline issues)
    p.write_text(json.dumps(d, indent=2) + "\n")

    oifm_id = d.get("oifm_id", "UNKNOWN")
    return f"{new_name}|{oifm_id}"


def main():
    parser = argparse.ArgumentParser(description="Fix finding model stubs")
    parser.add_argument("filepath", nargs="?", help="Path to .fm.json file")
    parser.add_argument("--name", help="Override finding name")
    parser.add_argument("--description", help="Override description")
    parser.add_argument("--synonyms", nargs="*", help="Override synonyms list")
    parser.add_argument(
        "--contributor",
        nargs="*",
        default=["hoodcm", "OIDM"],
        help="Contributor key(s) (default: hoodcm OIDM)",
    )
    parser.add_argument(
        "--batch",
        action="store_true",
        help="Read batch config from stdin (JSON)",
    )

    args = parser.parse_args()

    if args.batch:
        config = json.load(sys.stdin)
        # Support both "contributor"/"contributors" (string or list)
        raw_contrib = config.get("contributors", config.get("contributor"))
        if isinstance(raw_contrib, str):
            contributors = [raw_contrib]
        elif isinstance(raw_contrib, list):
            contributors = raw_contrib
        else:
            contributors = ["hoodcm", "OIDM"]
        for filepath, overrides in config.get("models", {}).items():
            result = fix_model(filepath, overrides, contributors)
            if result:
                print(result)
    elif args.filepath:
        overrides = {}
        if args.name:
            overrides["name"] = args.name
        if args.description:
            overrides["description"] = args.description
        if args.synonyms is not None:
            overrides["synonyms"] = args.synonyms
        result = fix_model(args.filepath, overrides, args.contributor)
        if result:
            print(result)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
