import json
import os
from pathlib import Path
from collections import defaultdict

def investigate_duplicates():
    """Investigate which CDEs are generating duplicate filenames."""
    
    input_dir = "cdes/definitions"
    output_dir = "defs/findings_from_cdes"
    
    # Dictionary to track filename -> list of CDEs that generate it
    filename_to_cdes = defaultdict(list)
    
    # Process all CDE files to see what filenames they would generate
    for filename in os.listdir(input_dir):
        if filename.endswith(".cde.json"):
            input_file = os.path.join(input_dir, filename)
            
            try:
                with open(input_file, "r", encoding="utf-8") as f:
                    cde_data = json.load(f)
                
                # Get the CDE name and ID
                cde_name = cde_data.get("name", "Unknown")
                cde_id = cde_data.get("id", "Unknown")
                
                # Generate the filename that would be created
                # This mimics the model_file_name function behavior
                safe_name = cde_name.lower().replace(" ", "_").replace("-", "_")
                safe_name = "".join(c for c in safe_name if c.isalnum() or c == "_")
                filename_generated = f"{safe_name}.fm.json"
                
                # Track which CDEs generate this filename
                filename_to_cdes[filename_generated].append({
                    "cde_id": cde_id,
                    "cde_name": cde_name,
                    "source_file": filename
                })
                
            except Exception as e:
                print(f"Error processing {input_file}: {str(e)}")
    
    # Find duplicates
    print("="*80)
    print("DUPLICATE FILENAME INVESTIGATION")
    print("="*80)
    
    duplicates_found = False
    total_duplicates = 0
    
    for filename, cde_list in filename_to_cdes.items():
        if len(cde_list) > 1:
            duplicates_found = True
            total_duplicates += len(cde_list) - 1
            
            print(f"\n📁 Filename: {filename}")
            print(f"   Generated by {len(cde_list)} CDEs:")
            
            for i, cde_info in enumerate(cde_list):
                print(f"   {i+1}. {cde_info['cde_id']} - {cde_info['cde_name']}")
                print(f"      Source: {cde_info['source_file']}")
            
            print(f"   → This will result in {len(cde_list) - 1} overwrites")
    
    if not duplicates_found:
        print("\n✅ No duplicate filenames found!")
    else:
        print(f"\n📊 SUMMARY:")
        print(f"   Total duplicate filenames: {len([f for f, cdes in filename_to_cdes.items() if len(cdes) > 1])}")
        print(f"   Total overwrites that will occur: {total_duplicates}")
        
        # Show which CDEs will be "lost" (overwritten)
        print(f"\n⚠️  CDEs that will be overwritten (content lost):")
        for filename, cde_list in filename_to_cdes.items():
            if len(cde_list) > 1:
                # All but the last one will be overwritten
                overwritten_cdes = cde_list[:-1]
                final_cde = cde_list[-1]
                
                print(f"\n   {filename}:")
                print(f"     Will keep: {final_cde['cde_id']} ({final_cde['cde_name']})")
                print(f"     Will lose: {', '.join([cde['cde_id'] for cde in overwritten_cdes])}")
    
    print("\n" + "="*80)

if __name__ == "__main__":
    investigate_duplicates()
